import type { Resident } from "./types";

export const residentMockData: Resident[] = [
  {
    id: "res-001",
    residentCode: "NH-2026-001",
    fullName: "Eleanor Rigby",
    dateOfBirth: "1942-08-18",
    gender: "female",
    roomNumber: "A-104",
    admissionDate: "2026-01-12",
    careLevel: "assisted_living",
    status: "admitted",
    assignedNurse: "Sarah Johnson, RN",
    assignedDoctor: "Dr. Michael Brown",
    primaryDiagnosis: "Hypertension, Type 2 Diabetes",
    emergencyContactName: "Paul Rigby",
    emergencyContactPhone: "(415) 555-0128",
  },
  {
    id: "res-002",
    residentCode: "NH-2026-002",
    fullName: "Robert Williams",
    dateOfBirth: "1938-03-04",
    gender: "male",
    roomNumber: "B-210",
    admissionDate: "2026-02-03",
    careLevel: "skilled_nursing",
    status: "under_evaluation",
    assignedNurse: "Linda Green, LPN",
    assignedDoctor: "Dr. John Davis",
    primaryDiagnosis: "Post-stroke rehabilitation",
    emergencyContactName: "Martha Williams",
    emergencyContactPhone: "(212) 555-0184",
  },
  {
    id: "res-003",
    residentCode: "NH-2026-003",
    fullName: "Patricia Clark",
    dateOfBirth: "1947-11-27",
    gender: "female",
    roomNumber: "M-016",
    admissionDate: "2026-03-18",
    careLevel: "memory_care",
    status: "admitted",
    assignedNurse: "Emily Carter, RN",
    assignedDoctor: "Dr. Petra Winsburry",
    primaryDiagnosis: "Alzheimer's disease",
    emergencyContactName: "Nancy Clark",
    emergencyContactPhone: "(646) 555-0199",
  },
  {
    id: "res-004",
    residentCode: "NH-2026-004",
    fullName: "George Miller",
    dateOfBirth: "1951-06-09",
    gender: "male",
    admissionDate: "2026-04-22",
    careLevel: "independent",
    status: "pending",
    assignedNurse: "Sarah Johnson, RN",
    assignedDoctor: "Dr. Emily Smith",
    primaryDiagnosis: "Chronic obstructive pulmonary disease",
    emergencyContactName: "Thomas Miller",
    emergencyContactPhone: "(305) 555-0152",
  },
  {
    id: "res-005",
    residentCode: "NH-2025-118",
    fullName: "Margaret Thompson",
    dateOfBirth: "1936-12-30",
    gender: "female",
    roomNumber: "C-302",
    admissionDate: "2025-10-08",
    careLevel: "assisted_living",
    status: "discharged",
    assignedNurse: "Anna Wilson, RN",
    assignedDoctor: "Dr. Linda Green",
    primaryDiagnosis: "Osteoarthritis",
    emergencyContactName: "Grace Thompson",
    emergencyContactPhone: "(617) 555-0171",
  },
  {
    id: "res-006",
    residentCode: "NH-2026-006",
    fullName: "Harold Bennett",
    dateOfBirth: "1940-02-14",
    gender: "male",
    roomNumber: "A-112",
    admissionDate: "2026-05-01",
    careLevel: "skilled_nursing",
    status: "admitted",
    assignedNurse: "Daniel Lee, RN",
    assignedDoctor: "Dr. Michael Brown",
    primaryDiagnosis: "Congestive heart failure",
    emergencyContactName: "Olivia Bennett",
    emergencyContactPhone: "(702) 555-0104",
  },
];
