export const APP_ROUTES = {
    LANDING: "/",
    DASHBOARD: "/dashboard",
    RESIDENTS: "/residents",
    RESIDENT_RECEPTION: "/residents/reception",
    INTAKE_ASSESSMENT: "/intake-assessment",
    DOCTOR_SCHEDULE: "/doctor-schedule",
    STAFF_SCHEDULE: "/staff-schedule",
    EMAR: "/emar",
    MEDICATION: "/medication",
    CARE_PLAN: "/care-plan",
    MEAL_DIET: "/meal-diet",
    BILLING: "/billing",
    INCIDENT_REPORT: "/incident-report",
    FAMILY_PORTAL: "/family-portal",
    LOGIN: "/login",
    REGISTER: "/login/register",
    FORGOT_PASSWORD: "/login/forgot-password",
    ENTER_NEW_PASSWORD: "/login/enter-new-password",
    SIGN_IN: "/sign-in",
    SIGN_UP: "/sign-up",
} as const;
